[CmdletBinding()]
param(
    [string]$Version = "0.9.2",
    [string]$OutputDirectory = ".\build\release",
    [string]$TextureSourceRoot = ".\build\diagnostics\texture_goal",
    [string]$CrtDirectory = ""
)
$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$resolvedOutput = if ([IO.Path]::IsPathRooted($OutputDirectory)) { [IO.Path]::GetFullPath($OutputDirectory) } else { [IO.Path]::GetFullPath((Join-Path (Get-Location) $OutputDirectory)) }
$staging = Join-Path $resolvedOutput "SotE-Recomp-$Version"
$zipPath = "$staging.zip"
if ((Test-Path -LiteralPath $staging) -or (Test-Path -LiteralPath $zipPath)) { throw 'Release output already exists; choose a new output directory.' }
$buildDir = Join-Path $repoRoot 'build\runtime\Release'
if (-not $CrtDirectory) {
    $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
    $vs = & $vswhere -latest -products '*' -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
    $crt = Get-ChildItem -LiteralPath "$vs\VC\Redist\MSVC" -Directory | Where-Object { $_.Name -match '^14\.' } | Sort-Object Name -Descending | Select-Object -First 1
    $CrtDirectory = Join-Path $crt.FullName 'x64\Microsoft.VC143.CRT'
}
foreach ($name in @('sote_recomp.exe','SDL2.dll','dxcompiler.dll','dxil.dll')) {
    if (-not (Test-Path -LiteralPath "$buildDir\$name")) { throw "Missing runtime: $name" }
}
foreach ($source in @('rom_source_v2','captured_source','dynamic_source_v1')) {
    if (-not (Test-Path -LiteralPath "$TextureSourceRoot\$source\source_baseline.json")) { throw "Missing texture source: $source" }
}
New-Item -ItemType Directory -Path $staging -Force | Out-Null
Copy-Item -LiteralPath "$buildDir\sote_recomp.exe" -Destination "$staging\Shadows of the Empire.exe"
foreach ($name in @('SDL2.dll','dxcompiler.dll','dxil.dll')) { Copy-Item -LiteralPath "$buildDir\$name" -Destination $staging }
foreach ($name in @('msvcp140.dll','msvcp140_1.dll','msvcp140_2.dll','msvcp140_atomic_wait.dll','msvcp140_codecvt_ids.dll','vcruntime140.dll','vcruntime140_1.dll','concrt140.dll','vcruntime140_threads.dll')) {
    Copy-Item -LiteralPath "$CrtDirectory\$name" -Destination $staging
}
Copy-Item -LiteralPath "$repoRoot\config\CONTROLS_MODERN.INI" -Destination $staging
# Settings are intentionally generated by the game instead of shipping a developer's settings.
$textureRoot = New-Item -ItemType Directory -Path "$staging\texture_upgrade"
foreach ($pair in @(@('rom_source_v2','rom'),@('captured_source','runtime_static'),@('dynamic_source_v1','runtime_changing'))) {
    Copy-Item -LiteralPath "$TextureSourceRoot\$($pair[0])" -Destination "$textureRoot\$($pair[1])" -Recurse
}
Copy-Item -LiteralPath "$repoRoot\tools\Build-HD-Pack.ps1" -Destination $staging
foreach ($pair in @(@('RELEASE_0.9.2.md','README.md'),@('TEXTURE_PACKS_USER.md','TEXTURE_PACKS.md'),@('MODERN_AIM.md','MODERN_AIM.md'),@('LEEBO_VOICES_USER.md','LEEBO_VOICES.md'))) {
    Copy-Item -LiteralPath "$repoRoot\docs\$($pair[0])" -Destination "$staging\$($pair[1])"
}
$toolsDir = New-Item -ItemType Directory -Path "$staging\texture_tools"
foreach ($name in @('extract_rom_textures.py','extract_rom_segments.py','rt64_tmem_hash.py','sote_texture_pack.py','convert_rt64_texture_dumps.py','build_dynamic_texture_pack.py','build_user_texture_pack.py','verify_tmem_hash.py','texture_coverage_capture.ps1','requirements.txt')) {
    Copy-Item -LiteralPath "$repoRoot\tools\$name" -Destination $toolsDir
}
$licenses = New-Item -ItemType Directory -Path "$staging\licenses"
Copy-Item -LiteralPath "$repoRoot\docs\licenses\DXC-LICENSE.txt" -Destination $licenses
Copy-Item -LiteralPath "$repoRoot\docs\licenses\JSON-LICENSE.txt" -Destination $licenses
Copy-Item -LiteralPath "$repoRoot\third_party\rt64\src\contrib\imgui\LICENSE.txt" -Destination "$licenses\imgui-LICENSE.txt"
foreach ($dependency in @('miniz','o1heap')) {
    Copy-Item -LiteralPath "$repoRoot\third_party\N64ModernRuntime\thirdparty\$dependency\LICENSE" -Destination "$licenses\$dependency-LICENSE.txt"
}
foreach ($dependency in @('fmt','rabbitizer','sljit','tomlplusplus')) {
    Copy-Item -LiteralPath "$repoRoot\third_party\N64ModernRuntime\N64Recomp\lib\$dependency\LICENSE" -Destination "$licenses\$dependency-LICENSE.txt"
}
foreach ($dependency in @('D3D12MemoryAllocator','VulkanMemoryAllocator')) {
    Copy-Item -LiteralPath "$repoRoot\third_party\rt64\src\contrib\plume\contrib\$dependency\LICENSE.txt" -Destination "$licenses\$dependency-LICENSE.txt"
}
foreach ($dependency in @('plume','stb','xxHash','zstd','spirv-cross','re-spirv','hlslpp','ddspp','im3d','implot','nativefiledialog-extended')) {
    Copy-Item -LiteralPath "$repoRoot\third_party\rt64\src\contrib\$dependency\LICENSE" -Destination "$licenses\$dependency-LICENSE.txt"
}
Copy-Item -LiteralPath "$repoRoot\third_party\rt64\LICENSE" -Destination "$licenses\RT64-LICENSE.txt"
Copy-Item -LiteralPath "$repoRoot\third_party\N64ModernRuntime\COPYING" -Destination "$licenses\N64ModernRuntime-COPYING.txt"
Copy-Item -LiteralPath "$repoRoot\third_party\N64Recomp\LICENSE" -Destination "$licenses\N64Recomp-LICENSE.txt"
Copy-Item -LiteralPath "$repoRoot\third_party\rt64\src\contrib\mupen64plus-win32-deps\SDL2-2.26.3\COPYING.txt" -Destination "$licenses\SDL2-COPYING.txt"
foreach ($item in Get-ChildItem -LiteralPath $staging -Recurse -File) {
    if ($item.Name -eq 'main.bin' -or $item.Extension -in @('.z64','.n64','.v64','.wav','.ogg','.tmem','.log')) { throw "Unexpected release file: $($item.FullName)" }
}
if (Test-Path -LiteralPath "$staging\textures") { throw 'Source textures must not be installed as active replacements.' }
Compress-Archive -Path "$staging\*" -DestinationPath $zipPath -CompressionLevel Optimal
$hash = (Get-FileHash -LiteralPath $zipPath -Algorithm SHA256).Hash.ToLowerInvariant()
[IO.File]::WriteAllText("$zipPath.sha256", "$hash  $([IO.Path]::GetFileName($zipPath))`n")
Write-Host "Release package: $zipPath"
Write-Host "SHA-256: $hash"
